### ISSUE TITLE
non-exhaustive patterns

### ISSUE THREAD

**Issue by cocreature** [MedeaMelana/stack-prism#3]
When trying to compile [ide-backend-client](https://github.com/chrisdone/ide-backend-client) with GHC 7.10.

```
src/IdeSession/Client/JsonAPI.hs:1:1:
    Exception when trying to run compile-time code:
      Data/StackPrism/TH.hs:74:27-63: Non-exhaustive patterns in lambda

    Code: deriveStackPrismsWith prismNameForConstructor ''Maybe
```

This is because you are just ignoring the `KindedTV` case. Apparently ghc changed it's output in one case from a PlainTV to a KindedTV which caused the problem in ide-backend-client, but that pattern match was not exhaustive even before GHC 7.10.
Chris Done [figured out](https://github.com/chrisdone/ide-backend-client/issues/1#issuecomment-89994523) a minimal example of how the output changed:

GHC 7.8.4:

```
Prelude Language.Haskell.TH> putStrLn $(reify ''Maybe >>= stringE . show)
TyConI (DataD [] Data.Maybe.Maybe [PlainTV a_1627399042] 
[NormalC Data.Maybe.Nothing [],NormalC Data.Maybe.Just [(NotStrict,VarT a_1627399042)]] 
[])
```

GHC 7.10:

```
Prelude Language.Haskell.TH> putStrLn $(reify ''Maybe >>= stringE . show)
TyConI (DataD [] GHC.Base.Maybe [KindedTV a_1627404217 StarT]
[NormalC GHC.Base.Nothing [],NormalC GHC.Base.Just [(NotStrict,VarT a_1627404217)]] 
[])
```

**Comment by MedeaMelana** [comment]
Thanks for reporting! I've pushed version 0.1.3 that fixes this. Please let me know if you encounter any other issues.

**Comment by cocreature** [comment]
Thanks for the quick fix!

**Comment by MedeaMelana** [comment]
No problem.
